# Changes here will be overwritten by Copier

_commit: 0.1.67
_src_path: git@bbpgitlab.epfl.ch:neuromath/python-template.git
author_email: ''
author_name: Blue Brain Project, EPFL
copyright_license: Apache License 2.0
copyright_year: '2022'
distribution_name: synthdb
download_url: https://github.com/BlueBrain/synthdb
init_git: false
maintainer: Adrien Berchet
package_name: synthdb
project_description: Small database to host synthesis-related files and integrated
    tools.
project_name: SynthDB
project_url: https://synthdb.readthedocs.io
repository_name: synthdb
repository_namespace: BlueBrain
repository_provider: github
setup_codeql: false
ssh_url: git@github.com:BlueBrain/synthdb.git
team_name: ''
tracker_url: https://github.com/BlueBrain/synthdb/issues
use_pyproject_toml: false
version: 0.0.3.dev0

# End of Copier answers
