# Changes here will be overwritten by Copier

_commit: 0.1.63
_src_path: git@bbpgitlab.epfl.ch:neuromath/python-template.git
author_email: bbp-ou-cells@groupes.epfl.ch
author_name: bbp-ou-cells
copyright_license: BBP-internal-confidential
copyright_year: '2022'
distribution_name: synthdb
download_url: https://bbpgitlab.epfl.ch/neuromath/synthdb
init_git: false
maintainer: ''
package_name: synthdb
project_description: Small database to host synthesis-related files and integrated
    tools.
project_name: SynthDB
project_url: https://bbpteam.epfl.ch/documentation/projects/synthdb
repository_name: synthdb
repository_namespace: neuromath
repository_provider: gitlab
setup_codeql: false
ssh_url: git@bbpgitlab.epfl.ch:neuromath/synthdb.git
team_name: neuromath
tracker_url: https://bbpteam.epfl.ch/project/issues/projects/CELLS/issues
use_pyproject_toml: false
version: 0.0.3.dev0

# End of Copier answers
