"""Create morphology release table.

Revision ID: 0002
Revises: 0001
Create Date: 2022-07-15 12:54:48.298105

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    """Operations to perform an upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "morph_releases",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gpfs_path", sa.String(), nullable=False),
        sa.Column("pip_list", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    """Operations to perform an downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("morph_releases")
    # ### end Alembic commands ###
