"""Add column for luigi_config in the morph_releases table.

Revision ID: 0003
Revises: 0002
Create Date: 2022-07-19 11:17:17.030540

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    """Operations to perform an upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("morph_releases", sa.Column("luigi_config", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Operations to perform an downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("morph_releases", "luigi_config")
    # ### end Alembic commands ###
